name:                dit
version:             0.1.0.0
github:              "gillchristian/dit"
license:             BSD3
author:              "Christian Gill"
maintainer:          "gillchristian@gmail.com"
copyright:           "2021 Christian Gill"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/gillchristian/dit#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- datetime
- directory
- filepath
- nonempty-containers
- optparse-applicative
- parsec
- raw-strings-qq
- sqlite-simple
- text
- time
- tomland
- transformers
- unordered-containers

library:
  source-dirs: src

executables:
  dit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - dit

tests:
  dit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dit
